[workspace]
changelog_update = true
dependencies_update = true

git_release_enable = true
git_tag_enable = true
git_release_type = "auto"

release_always = false
publish = true
publish_timeout = "10m"
publish_allow_dirty = false

semver_check = true
release_commits = "^(release|feat|fix)[(:]"
pr_branch_prefix = "release-plz-"
pr_labels = ["release"]

[[package]]
name = "multiio"
changelog_path = "CHANGELOG.md"
